// Auto-generated by BugHunt. Correctness-first typed JS/TS fallback.
import js from "@eslint/js";
import { defineConfig } from "eslint/config";
import tseslint from "typescript-eslint";

export default defineConfig(
  { ignores: ["node_modules/**", "dist/**", "build/**", ".next/**", ".bughunt/**", ".venv/**", "venv/**", "env/**", ".direnv/**", ".git/**", ".hg/**", ".svn/**", ".tox/**", ".nox/**", ".mypy_cache/**", ".pytest_cache/**", ".ruff_cache/**", ".pyre/**", ".coverage/**", "htmlcov/**", "mutants/**", "__pypackages__/**", "site-packages/**", ".agents/**", ".claude/**", ".codex/**", ".pi/**", ".omp/**", ".hermes/**", ".trace/**", ".benchmarks/**", ".complexipy_cache/**", ".import_linter_cache/**", "**/dist/**", "**/build/**", "**/.next/**", "**/node_modules/**", "**/.venv/**", "**/venv/**", "**/coverage/**", "**/htmlcov/**"] },
  {
    files: ["**/*.{ts,tsx,mts,cts}"],
    extends: [
      js.configs.recommended,
      tseslint.configs.strictTypeChecked,
    ],
    languageOptions: {
      parserOptions: {
        projectService: true,
      },
    },
    rules: {
      "@typescript-eslint/no-misused-promises": "error",
      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-unnecessary-condition": "error",
      "@typescript-eslint/only-throw-error": "error",
      "@typescript-eslint/require-await": "error",
      "@typescript-eslint/return-await": ["error", "error-handling-correctness-only"],
      "@typescript-eslint/switch-exhaustiveness-check": "error",
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-non-null-assertion": "warn"
    }
  },
  {
    files: ["**/*.{js,mjs,cjs,jsx}"],
    extends: [js.configs.recommended],
    rules: {
      "array-callback-return": "error",
      "eqeqeq": "error",
      "no-constant-binary-expression": "error",
      "no-constructor-return": "error",
      "no-promise-executor-return": "error",
      "no-self-compare": "error",
      "no-template-curly-in-string": "error",
      "no-unmodified-loop-condition": "error",
      "require-atomic-updates": "error"
    }
  }
);
